### ISSUE TITLE
Rest request failed

### ISSUE THREAD

**Issue by MattMello88** [Code4Delphi/Delphi-AI-Developer#1]
Na minha aplicação fica gerando esta mensagem de erro da imagem abaixo, esteve funcionando e parou dando esta msg.

![image](https://github.com/Code4Delphi/Delphi-AI-Developer/assets/1126417/6eb9003e-043f-4903-8c2c-9ef7fe6582bf)

**Comment by Cesar4D** [comment]
Olá Matheus. Vamos solucionar esse problema, vou te fazer algumas perguntas: Qual a versão do seu Delphi? Essa unit a qual você quer refatorar, qual o número de linhas dela? Se você fizer uma pergunta com a opção "Use current unit code in query" (botão do lado esquerdo do botão de Send) desmarcado o erro acontece também?
Agradeço o seu feedback.

**Comment by atorrecontrole** [comment]
descobri o que era, fiquei off line quando estava fazendo a consulta. Talvez seja uma melhoria, identificar que esta offline.

**Comment by Cesar4D** [comment]
Ótimo Matheus, que bom que deu certo. Estamos trabalhando em melhorias no plugin, e vou adicionar essa sua dica a lista. Muito obrigado.

**Comment by Cesar4D** [comment]
Olá Matheus. Seguindo sua dica, adicionamos a mensagem "* Check Your Internet Connection *" ao tentar usar o plugin estando offline.
Irei fechar a Issue, caso ache necessário pode reabri-la ou criar novas.
Obrigado pela sugestão.
