### ISSUE TITLE
Can we have a Shortkey added to the "Send" button in the chat window?

### ISSUE THREAD

**Issue by gaddlord** [Code4Delphi/Delphi-AI-Developer#12]
Can we have a Shortkey added to the "Send" button in the chat window?

This would ease the 

1. type prompt
2. send prompt
3. read response
4. type another prompt
5. send new prompt
... workflow witohut the need of a mouse.

Display the hosrtcut in a button Hint such as "Send Pormpt (Alt+S)"

**Comment by Cesar4D** [comment]
Hi Gad D Lord,

Actually, there is already a shortcut for this: Ctrl + Enter. I forgot to include a tooltip on the screen about the shortcut or mention it in the documentation.

See if this helps you. If not, please let me know so we can make some changes.

Thanks for your suggestion!

**Comment by Cesar4D** [comment]
Great, thanks a lot for getting back to me.
