### ISSUE TITLE
Add support for Github Copilot

### ISSUE THREAD

**Issue by ScruffyDerHausmeister** [Code4Delphi/Delphi-AI-Developer#13]
Please add support for Github Copilot.

**Comment by Cesar4D** [comment]
Hi, thanks for your tip. Unfortunately, it is not possible to integrate with GitHub Copilot. It was our first choice; however, they do not provide any form of integration. Thank you.

**Comment by ScruffyDerHausmeister** [comment]
Thank you for clarifying.
