### ISSUE TITLE
Add support for Github Copilot

### ISSUE THREAD

**Issue by daharper** [Code4Delphi/Delphi-AI-Developer#14]
Firstly, thank you kindly for this excellent initiative, and all your hard work.

Many developers already have a subscription to Github Copilot, which is supported in a number of IDEs like VSCode, VS Studio, JetBrains IDEs etc. It would be wonderful to use the same Github Copilot subscription with Delphi.

**Comment by Cesar4D** [comment]
Hi, thanks for the tip. Unfortunately, it is not possible to integrate with GitHub Copilot. It was our first choice, however, they do not provide any form of integration. Thanks.

**Comment by daharper** [comment]
Hi Cesar, I'm using it via VS Code, VS Studio, and all of the JetBrains IDEs via plugins. Perhaps this is something Embarcadero could negotiate with Github? Anyways, thanks for your reply, keep up the great work!
