### ISSUE TITLE
Integração com o lhama 3.1 local;

### ISSUE THREAD

**Issue by wendelswl** [Code4Delphi/Delphi-AI-Developer#8]
#### Seria bastante interessante uma integração com o Lhama em ambiente local, desta forma os desenvolvedores não necessitariam compartilhar seus códigos com IA, facilitaria nos seguintes aspectos:

- Não compartilhar código dos desenvolvedores com a IA externa;
- Através do Ollama é possível consumir a api da IA;
- Resposta sem limites de token;

**Comment by Cesar4D** [comment]
Olá Wendel. Muito boa a sua dica.
Estamos implementando a integração com IA off-line, com isso será possível usar o Llama 3.1. Porém estamos enfrentando problemas com hardware para realizar os testes, pois para rodar um modelo como Llama 3.1 é necessário uma maquina muito boa com uma ótima placa de vídeo.
Agradeço sua dica e continue acompanhando o projeto, que em breve teremos várias novidades

**Comment by Cesar4D** [comment]
Hi, Wendel. The integration with Llama 3.1 local has been completed and is now available for use. To use it, simply update the plugin and configure it. We have created complete documentation showing the step-by-step process; it is available at this link: [https://github.com/Code4Delphi/Delphi-AI-Developer#-ai-off-line](https://github.com/Code4Delphi/Delphi-AI-Developer#-ai-off-line)
